import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import PageTransition from "./components/PageTransition";
import StairTransition from "./components/StairTransition";
import Footer from "./components/Footer";

const oswald = Oswald({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oswald.className} bg-custom-image bg-cover bg-center bg-fixed bg-no-repeat relative text-white`}>
        <StairTransition />
        <Header />
        <PageTransition>
          {children}
        </PageTransition>
        <Footer />
      </body>
    </html>
  );
}
